baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Max Cairney-Leeming
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

# taxonomies:
#     tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 3 
        - name: Notes
          url: notes/
          weight: 4

params:
    description: "This is Max Cairney-Leeming's personal website."
    author: Max Cairney-Leeming
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","notes"]
    NewsSections: ["news"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Max Cairney-Leeming
          subtitle: "I am a PhD Student at the Institute of Science and Technology Austria (ISTA), near-ish Vienna, under the supervision of Christoph Lampert. I am also a member of the ELLIS PhD Program, and so co-supervised by Amartya Sanyal at the University of Copenhagen."
          imageUrl: "me.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Notes
              url: notes/
            # - name: Books
            #   url: books/
            # - name: Courses
            #   url: courses/
            # - name: Tags
            #   url: tags/
            - name: Archive
              url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        # to do: write a new CV!
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:max@cairneyleeming.co.uk
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=tklkAnwAAAAJ
        - name: GitHub
          url: https://github.com/mtcairneyleeming
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        - name: Bluesky
          url: https://bsky.app/profile/maxcl.co.uk

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Max Cairney-Leeming"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2